sudo: required

language: ruby

env:
  - DOCKERFILE=tests/dockerfiles/CentOS_7.Dockerfile IMGNAME=centos7-grgsm


services:
  - docker

before_install:
  - cat $DOCKERFILE > Dockerfile ; docker build -t $IMGNAME .

script:
#  - docker run -it --rm $IMGNAME sh -c 'cd /src/build;make test'
  - docker run -it --rm $IMGNAME /src/tests/scripts/decode.sh
  - docker run -it --rm $IMGNAME /src/tests/scripts/decrypt.sh
