sudo: required

language: ruby

env:
  - DOCKERFILE=tests/dockerfiles/Debian_testing.docker IMGNAME=gr-gsm:debian_testing
#  - DOCKERFILE=tests/dockerfiles/Ubuntu_16_04.docker IMGNAME=ubu16.04-grgsm
#  - DOCKERFILE=tests/dockerfiles/Ubuntu_16_04_nolibosmo.docker IMGNAME=ubu16.04-grgsm-nolibosmo
  - DOCKERFILE=tests/dockerfiles/Kali.docker IMGNAME=gr-gsm:kali
#  - DOCKERFILE=tests/dockerfiles/Fedora_26.Dockerfile IMGNAME=fedora26-grgsm


services:
  - docker

before_install:
  - cat $DOCKERFILE > Dockerfile ; docker build -t "$DOCKER_USERNAME"/$IMGNAME .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$DOCKER_USERNAME"/$IMGNAME

script:
#  - docker run -it --rm $IMGNAME sh -c 'cd /src/build;make test'
  - docker run -it --rm "$DOCKER_USERNAME"/$IMGNAME /src/tests/scripts/decode.sh
  - docker run -it --rm "$DOCKER_USERNAME"/$IMGNAME /src/tests/scripts/decrypt.sh
